In [6]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("array b4 swap: ")
print(a)
a[[0,3],:]=a[[3,0],:]
print("array after swap: ")
print(a)

array b4 swap: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
array after swap: 
[[13 14 15 16]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]
